import { HttpStatus } from '@nestjs/common';

export const AUTH_ERROR = {
  USER_NOT_FOUND: 'AUTH.USER_NOT_FOUND',
  INVALID_PASSWORD: 'AUTH.INVALID_PASSWORD',
  EMAIL_EXISTS: 'AUTH.EMAIL_EXISTS',
  INVALID_TOKEN: 'AUTH.INVALID_TOKEN',
  INVALID_REFRESH_TOKEN: 'AUTH.INVALID_REFRESH_TOKEN',
  INVALID_OTP: 'AUTH.INVALID_OTP',
  QR_EXPIRED: 'AUTH.QR_EXPIRED',
  UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  USER_ALREADY_EXISTS: 'AUTH.USER_ALREADY_EXISTS',
  SESSION_REVOKED: 'AUTH.SESSION_REVOKED',
  EMAIL_NOT_VERIFIED: 'AUTH.EMAIL_NOT_VERIFIED',
  SOCIAL_LOGIN_NOT_ALLOWED: 'AUTH.SOCIAL_LOGIN_NOT_ALLOWED',
  SCOPE_MISMATCH: 'AUTH.SCOPE_MISMATCH',
  ACCOUNT_ALREADY_EXISTS: 'AUTH.ACCOUNT_ALREADY_EXISTS',
  EMAIL_ALREADY_VERIFIED: 'AUTH.EMAIL_ALREADY_VERIFIED',
  OTP_EXPIRED: 'AUTH.OTP_EXPIRED',
  ADMIN_NOT_APPROVED: 'AUTH.ADMIN_NOT_APPROVED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];

export const AUTH_ERROR_STATUS: Record<keyof typeof AUTH_ERROR, HttpStatus> = {
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  INVALID_PASSWORD: HttpStatus.UNAUTHORIZED,
  EMAIL_EXISTS: HttpStatus.CONFLICT,
  INVALID_TOKEN: HttpStatus.UNAUTHORIZED,
  INVALID_REFRESH_TOKEN: HttpStatus.UNAUTHORIZED,
  INVALID_OTP: HttpStatus.UNAUTHORIZED,
  QR_EXPIRED: HttpStatus.GONE,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  USER_ALREADY_EXISTS: HttpStatus.CONFLICT,
  SESSION_REVOKED: HttpStatus.UNAUTHORIZED,
  EMAIL_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  SOCIAL_LOGIN_NOT_ALLOWED: HttpStatus.FORBIDDEN,
  SCOPE_MISMATCH: HttpStatus.NOT_FOUND,
  ACCOUNT_ALREADY_EXISTS: HttpStatus.CONFLICT,
  EMAIL_ALREADY_VERIFIED: HttpStatus.CONFLICT,
  OTP_EXPIRED: HttpStatus.GONE,
  ADMIN_NOT_APPROVED: HttpStatus.FORBIDDEN,
} as const;
