import { HttpStatus } from '@nestjs/common';

export const AUTH_ERROR = {
  USER_NOT_FOUND: 'AUTH.USER_NOT_FOUND',
  INVALID_PASSWORD: 'AUTH.INVALID_PASSWORD',
  EMAIL_EXISTS: 'AUTH.EMAIL_EXISTS',
  INVALID_REFRESH_TOKEN: 'AUTH.INVALID_REFRESH_TOKEN',
  INVALID_OTP: 'AUTH.INVALID_OTP',
  QR_EXPIRED: 'AUTH.QR_EXPIRED',
  UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];

export const AUTH_ERROR_STATUS: Record<AuthErrorCode, HttpStatus> = {
  [AUTH_ERROR.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AUTH_ERROR.INVALID_PASSWORD]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR.EMAIL_EXISTS]: HttpStatus.CONFLICT,
  [AUTH_ERROR.INVALID_REFRESH_TOKEN]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR.INVALID_OTP]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR.QR_EXPIRED]: HttpStatus.GONE,
  [AUTH_ERROR.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
};
