export const AUTH_ERROR = {
  USER_NOT_FOUND: "AUTH.USER_NOT_FOUND",
  INVALID_PASSWORD: "AUTH.INVALID_PASSWORD",
  EMAIL_EXISTS: "AUTH.EMAIL_EXISTS",
  INVALID_REFRESH_TOKEN: "AUTH.INVALID_REFRESH_TOKEN",
  INVALID_OTP: "AUTH.INVALID_OTP",
  QR_EXPIRED: "AUTH.QR_EXPIRED",
  UNAUTHORIZED: "AUTH.UNAUTHORIZED",
} as const;

export const CART_ERROR = {
  ITEM_NOT_FOUND: "CART.ITEM_NOT_FOUND",
  OUT_OF_STOCK: "CART.OUT_OF_STOCK",
  UNAUTHORIZED: "CART.UNAUTHORIZED",
} as const;

export type ErrorCode = (
  | typeof AUTH_ERROR
  | typeof CART_ERROR
)[keyof typeof AUTH_ERROR & keyof typeof CART_ERROR];
